home:
  rooms:
    Living:
      surfaces:
        shelving_unit:
          tasks:
            - method: "wipe"
              frequency: "weekly"
            - method: "wet wipe"
              frequency: "monthly"
        bed:
          tasks:
            - method: "make"
              frequency: "daily"
            - method: "wipe"
              frequency: "weekly"
        desk:
          tasks:
            - method: "wipe"
              frequency: "weekly"
            - method: "wet wipe"
              frequency: "monthly"
            - method: "tidy up"
              frequency: "daily"
    Kitchen:
      surfaces:
        cupboard:
          tasks:
            - method: "tidy up"
              frequency: "weekly"
            - method: "wet wipe"
              frequency: "weekly"
        table:
          tasks:
            - method: "tidy up"
              frequency: "daily"
            - method: "wet wipe"
              frequency: "daily"
  appliances:
    Refrigerator:
      tasks:
        - method: "wet wipe"
          frequency: "weekly"
        - method: "tidy up"
          frequency: "weekly"
        - method: "sort"
          frequency: "weekly"
    Stove/Oven:
      tasks:
        - method: "clean"
          frequency: "weekly"
    Dishwasher:
      tasks:
        - method: "refill"
          frequency: "weekly"
        - method: "wash up"
          frequency: "after use"
    Microwave:
      tasks:
        - method: "wipe"
          frequency: "weekly"