home:
  model: llama3.2:latest

task_management:
  home:
    rooms:
      Living:
        room_furnishings:
          Shelve:
            actions:
              - method: "wipe"
                frequency: "weekly"
              - method: "wet wipe"
                frequency: "monthly"
          desk:
            actions:
              - method: "wipe"
                frequency: "weekly"
              - method: "wet wipe"
                frequency: "monthly"
              - method: "tidy up"
                frequency: "daily"
      Kitchen:
        room_furnishings:
          cupboard:
            actions:
              - method: "tidy up"
                frequency: "weekly"
              - method: "wet wipe"
                frequency: "weekly"
          table:
            actions:
              - method: "tidy up"
                frequency: "daily"
              - method: "wet wipe"
                frequency: "daily"
          refrigerator:
            actions:
              - method: "wet wipe"
                frequency: "weekly"
              - method: "tidy up"
                frequency: "weekly"
              - method: "sort"
                frequency: "weekly"
          stove/oven:
            actions:
              - method: "clean"
                frequency: "weekly"
          dishwasher:
            actions:
              - method: "refill"
                frequency: "weekly"
              - method: "wash up"
                frequency: "daily"
          microwave:
            actions:
              - method: "wipe"
                frequency: "weekly"
